	var __wxAppData = {}; 	var __wxRoute; 	var __wxRouteBegin; 	var global = {}; 		define("utils/util.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 "use strict";var t=function(t){return(t=t.toString())[1]?t:"0"+t};module.exports={formatTime:function(e){var n=e.getFullYear(),r=e.getMonth()+1,o=e.getDate(),u=e.getHours(),i=e.getMinutes(),a=e.getSeconds();return[n,r,o].map(t).join("/")+" "+[u,i,a].map(t).join(":")}}; 
 			}); 		define("app.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 "use strict";App({onLaunch:function(){var n=this,s=wx.getStorageSync("logs")||[];s.unshift(Date.now()),wx.setStorageSync("logs",s),wx.login({success:function(n){}}),wx.getSetting({success:function(s){s.authSetting["scope.userInfo"]&&wx.getUserInfo({success:function(s){n.globalData.userInfo=s.userInfo,n.userInfoReadyCallback&&n.userInfoReadyCallback(s)}})}})},globalData:{userInfo:null}}); 
 			}); 	require("app.js");
 		__wxRoute = 'pages/index/index';__wxRouteBegin = true; 	define("pages/index/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 "use strict";getApp();Page({data:{win_h:0,isSixteenError:!1,animationTip:{},tip_content:"",bg_color:"",isFocusRGB:!1,isFocusSIX:!1,RGB:[],sixteenText:""},onLoad:function(t){try{var e=wx.getStorageSync("RGB"),s=wx.getStorageSync("SIXTEEN"),i=wx.getStorageSync("BG_COLOR");""==e&&""==s&&""==i?(console.log("null"),this.setData({RGB:[{id:"1",value:"255",isError:!1},{id:"2",value:"255",isError:!1},{id:"3",value:"255",isError:!1}],sixteenText:"FFFFFF",bg_color:"#FAFAFA"})):(console.log("full"),this.setData({RGB:e,sixteenText:s,bg_color:i}));var a=wx.getSystemInfoSync();this.setData({win_h:a.windowHeight})}catch(t){console.log("get system info error")}},updateRGBCallBack:function(t){var e=t.currentTarget.id-1,s=t.detail.value,i=this.data.RGB;if(i[e].value=s,""!=s){if(parseInt(s)<0||parseInt(s)>255)return i[e].isError=!0,this.setData({RGB:i}),void this.showTip("请输入0~255范围内的数字");if(parseInt(s)!=s)return i[e].isError=!0,this.setData({RGB:i}),void this.showTip("请输入整数类型的数字");i[e].isError=!1,this.setData({RGB:i}),i[0].isError||i[1].isError||i[2].isError||this.transformResult()}},updateSixtennCallBack:function(t){var e=t.detail.value;if(6==e.length){if(this.isOutRange(e))return this.setData({isSixteenError:!0}),void this.showTip("请输入正确的十六进制色值");this.setData({isSixteenError:!1});var s=this.SIXTEEN_TO_RGB(e);s[0].value,s[1].value,s[2].value;this.setData({RGB:s,bg_color:"#"+e})}},setRGBCallBack:function(t){},setSixteenCallBack:function(t){},onFocusCallBack:function(t){var e=t.currentTarget.id;if("rgb"==e)this.setData({isFocusRGB:!0,isFocusSIX:!1});else if("sixteen"==e)this.setData({isFocusRGB:!1,isFocusSIX:!0});else{if("cmyk"!=e)return;this.setData({isFocusRGB:!1,isFocusSIX:!1})}},rgbOnFocus:function(){this.setData({isFocusRGB:!0})},sixOnFocus:function(){this.setData({isFocusSIX:!0})},isOutRange:function(t){for(var e=["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"],s=0;s<6;s++)if(-1==e.indexOf(t.substring(s,s+1).toUpperCase()))return!0;return!1},transformResult:function(){var t=this.data.RGB,e=this.RGB_TO_SIXTEEN(t);this.setData({sixteenText:e,bg_color:"#"+e})},RGB_TO_SIXTEEN:function(t){var e=parseInt(t[0].value).toString(16).toUpperCase(),s=parseInt(t[1].value).toString(16).toUpperCase(),i=parseInt(t[2].value).toString(16).toUpperCase();return 1==e.length&&(e="0"+e),1==s.length&&(s="0"+s),1==i.length&&(i="0"+i),e+s+i},SIXTEEN_TO_RGB:function(t){var e=parseInt(t.substring(0,2),16),s=parseInt(t.substring(2,4),16),i=parseInt(t.substring(4,6),16),a=this.data.RGB;return a[0].value=e,a[1].value=s,a[2].value=i,a},showTip:function(t){var e=this;this.setData({tip_content:t});var s=setTimeout(function(){e.setData({tip_content:""}),clearTimeout(s)},2500)},onUnload:function(){try{wx.setStorageSync("RGB",this.data.RGB),wx.setStorageSync("SIXTEEN",this.data.sixteenText),wx.setStorageSync("BG_COLOR",this.data.bg_color)}catch(t){}}}); 
 			}); 	require("pages/index/index.js");
 		__wxRoute = 'pages/logs/logs';__wxRouteBegin = true; 	define("pages/logs/logs.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 "use strict";var t=require("../../utils/util.js");Page({data:{logs:[]},onLoad:function(){this.setData({logs:(wx.getStorageSync("logs")||[]).map(function(a){return t.formatTime(new Date(a))})})}}); 
 			}); 	require("pages/logs/logs.js");
 	